# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Lantern Client' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Lantern Client

  swift_version = "3.0"

  pod "PromiseKit", "~> 4.0"

  pod 'Starscream', '~> 2.0.3'

  pod 'HGCircularSlider', '~> 1.0.3'

  pod 'Freddy'

  pod 'RxSwift',    '~> 3.0'
  pod 'RxCocoa',    '~> 3.0'

end
